HomeLoanCaseStudy/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace HomeLoanCaseStudy.Controllers
{
    [NoDirectAccess]
    public class CalculatorController : Controller
    {
        // GET: Calculator
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Eligibility()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Eligibility(string monthlyIncome)
        {
            if (monthlyIncome != "")
            {
                int mI = Convert.ToInt32(monthlyIncome);

                double eligibleAmount = 0.6 * 60 * mI;
                eligibleAmount = Math.Round(eligibleAmount, 2);

                ViewData["MonthlyIncome"] = monthlyIncome;
                ViewData["InterestRate"] = 8.5;
                ViewData["EligibleAmount"] = eligibleAmount;

                return View();
            }
            else
            {
                ViewBag.Message = "Enter Monthly Salary";
                return View();
            }
        }

        [HttpGet]
        public ActionResult EmiCal()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EmiCal(string loanAmount, string tenure)
        {
            if (loanAmount != "" && tenure != "")
            {
                double ROI = 8.5;
                ROI /= (12 * 100);

                int lA = Convert.ToInt32(loanAmount);
                int tE = Convert.ToInt32(tenure) * 12;

                double emi = lA * ROI * (Math.Pow((1 + ROI), tE)) / (Math.Pow((1 + ROI), tE) - 1); // Formula for calculating Emi
                emi = Math.Round(emi, 2);

                ViewData["LoanAmount"] = loanAmount;
                ViewData["Tenure"] = tenure;
                ViewData["InterestRate"] = 8.5;
                ViewData["EMI"] = emi;

                return View();
            }
            else
            {
                ViewBag.Message = "Enter Loan Salary / Tenure";
                return View();
            }
        }
    }
}

HomeLoanCaseStudy/Controllers/UsersController.cs
using HomeLoanCaseStudy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace HomeLoanCaseStudy.Controllers
{
    [NoDirectAccess]
    public class UsersController : Controller
    {
        private readonly HomeLoanDbContext db = new HomeLoanDbContext();

        // GET: Users
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Users user)
        {
            bool Status = false;
            string message;

            if (ModelState.IsValid)
            {
                var isExist = IsEmailExist(user.EmailAddress);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "Email Already Exists");
                    return View(user);
                }

                user.Password = Crypto.Hash(user.Password);
                user.ConfirmPassword = Crypto.Hash(user.ConfirmPassword);

                db.Users.Add(user);
                db.SaveChanges();

                if (user.UserRole == "Customer")
                {
                    db.UserDetails.Add(new UserDetails() { Id = user.Id });
                    db.Loans.Add(new Loan() { Id = user.Id, InterestRate = 8.5f, ApprovalStatus = "Pending" });
                    db.SaveChanges();
                }
                message = "Registration Done Successfully!";
                Status = true;
            }
            else
            {
                message = "Invalid Request";
            }
            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View(user);
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Users user, string returnUrl)
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(user.EmailAddress)).FirstOrDefault();
            if (obj != null)
            {
                if (string.Compare(Crypto.Hash(user.Password), obj.Password) == 0)
                {
                    bool check = Request["RememberMe"].ToString() == "true,false";
                    FormsAuthentication.SetAuthCookie(user.EmailAddress, check);
                    if (Url.IsLocalUrl(returnUrl))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    ViewBag.Message = "Wrong Password";
                    return View(user);
                }
            }
            else
            {
                ViewBag.Message = "Email does not match with any existing user";
                return View(user);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        [NonAction]
        public bool IsEmailExist(string emailId)
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(emailId)).FirstOrDefault();
            return obj != null;
        }
    }
}

HomeLoanCaseStudy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NRSHLoans</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/Styles/homepage.css">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <div class="container user-select-none">
            <a class="navbar-brand" href="/">
                <img src="~/assets/HomeLoan.png" width="30" height="30" class="d-inline-block align-top me-1" alt="">
                NRSHLoans
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav me-auto">
                    <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About Us", "About", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Calculator
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Eligibility Calculator", "Eligibility", "Calculator", null, new { @class = "dropdown-item" })</li>
                            <li><hr class="dropdown-divider"></li>
                            <li>@Html.ActionLink("EMI Calculator", "EmiCal", "Calculator", null, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Application", "Index", "Application", null, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home", null, new { @class = "nav-link" })</li>
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    using (Html.BeginForm("Logout", "Users", FormMethod.Post, new { id = "logoutForm" }))
                    {
                        <button class="btn btn-outline-light me-2" type="button" onclick="location.href='javascript:document.getElementById(`logoutForm`).submit()'">
                            Logout<i class="fa fa-sign-out ms-2"></i>
                        </button>
                    }
                }
                else
                {
                    <button class="btn btn-outline-light me-2 nav-btns" type="button" onclick="location.href='@Url.Action("Login", "Users")'">
                        Login<i class="fa fa-user ms-2"></i>
                    </button>
                    <button class="btn btn-light nav-btns" type="button" onclick="location.href='@Url.Action("Register", "Users")'">
                        Register<i class="fa fa-user-plus ms-2"></i>
                    </button>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content text-white">
        @RenderBody()
    </div>
    <div class="container fixed-bottom text-center">
        <p class="footer-text user-select-none">&copy; @DateTime.Now.Year - Home Loan Application</p>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>