HomeLoanCaseStudy/Controllers/ApplicationController.cs
using HomeLoanCaseStudy.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeLoanCaseStudy.Controllers
{
    [Authorize]
    [NoDirectAccess]
    public class ApplicationController : Controller
    {
        private readonly HomeLoanDbContext db = new HomeLoanDbContext();

        // GET: Application
        public ActionResult Index()
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
            if (obj.UserRole == "Admin")
            {
                return RedirectToAction("Index", "Home");
            }

            var userDetailsObj = db.UserDetails.Where(ud => ud.Id.Equals(obj.Id)).FirstOrDefault();
            if(userDetailsObj.AccountNumber == null)
            {
                return RedirectToAction("PropertyDetails");
            }

            return RedirectToAction("Index", "LoanTracker");
        }

        public ActionResult PropertyDetails()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PropertyDetails(UserDetails userDetails)
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
            if (obj != null)
            {
                var userObj = db.UserDetails.Where(ud => ud.Id.Equals(obj.Id)).FirstOrDefault();
                var loanObj = db.Loans.Where(l => l.Id.Equals(obj.Id)).FirstOrDefault();
                if (loanObj.ApprovalStatus.Equals("Pending"))
                {
                    userObj.PropertyLocation = userDetails.PropertyLocation;
                    userObj.PropertyName = userDetails.PropertyName;
                    userObj.PropertyEstimatedAmount = userDetails.PropertyEstimatedAmount;
                    db.SaveChanges();
                    return RedirectToAction("EmploymentDetails");
                }
            }
            return View(userDetails);
        }

        public ActionResult EmploymentDetails()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmploymentDetails(UserDetails userDetails)
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
            if (obj != null)
            {
                var userObj = db.UserDetails.Where(ud => ud.Id.Equals(obj.Id)).FirstOrDefault();

                userObj.EmploymentType = userDetails.EmploymentType;
                userObj.MonthlySalary = userDetails.MonthlySalary;
                userObj.RetirementAge = userDetails.RetirementAge;
                userObj.OrganizationType = userDetails.OrganizationType;
                userObj.EmployerName = userDetails.EmployerName;
                double eligibleAmount = 0.6 * 60 * (double)userDetails.MonthlySalary;
                eligibleAmount = Math.Round(eligibleAmount, 2);
                userObj.MaxLoanAmount = eligibleAmount;
                db.SaveChanges();
                return RedirectToAction("LoanDetails");
            }
            return View(userDetails);
        }

        public ActionResult LoanDetails()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoanDetails(Loan loan)
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
            if (obj != null)
            {
                var userDetailsObj = db.UserDetails.Find(obj.Id);
                var loanObj = db.Loans.Where(l => l.Id.Equals(obj.Id)).FirstOrDefault();

                if (loan.LoanAmount > userDetailsObj.MaxLoanAmount)
                {
                    ViewBag.Message = "Loan Amount entered exceeds the maximum approved loan limit!";
                }
                else
                {
                    loanObj.Tenure = loan.Tenure;
                    loanObj.LoanAmount = loan.LoanAmount;
                    db.SaveChanges();
                    return RedirectToAction("PersonalDetails");
                }
            }
            return View(loan);
        }

        public ActionResult PersonalDetails()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PersonalDetails(UserDetails userDetails)
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
            if (obj != null)
            {
                var userObj = db.UserDetails.Where(ud => ud.Id.Equals(obj.Id)).FirstOrDefault();

                userObj.PhoneNumber = userDetails.PhoneNumber;
                userObj.DateOfBirth = userDetails.DateOfBirth;
                userObj.Gender = userDetails.Gender;
                userObj.PanNumber = userDetails.PanNumber;
                db.SaveChanges();
                return RedirectToAction("UploadDocuments");
            }
            return View(userDetails);
        }

        public ActionResult UploadDocuments()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadDocuments(HttpPostedFileBase[] file)
        {
            var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
            int id = obj.Id;
            string folder = Server.MapPath(string.Format("~/App_Data/files/{0}", id));
            string[] fileNames = new string[] { "PanCard", "SalarySlip", "LOA", "NOCfromBuilder", "AgreementToSale" };

            if (!Directory.Exists(folder))
            {
                Directory.CreateDirectory(folder);
                //ViewBag.Message = "Folder " + id.ToString() + " created successfully!";

                for (int i = 0; i < file.Length; i++)
                {
                    HttpPostedFileBase fileItem = file[i];

                    if (fileItem != null && fileItem.ContentLength > 0)
                    {
                        try
                        {
                            string fileName = fileNames[i] + ".pdf";
                            string fullPath = Path.Combine(folder, fileName);
                            fileItem.SaveAs(fullPath);
                            ViewBag.Message = "Files uploaded successfully with id = " + id;
                        }
                        catch (Exception ex)
                        {
                            ViewBag.Message = "ERROR:" + ex.Message.ToString();
                        }
                    }
                    else
                    {
                        ViewBag.Message = "You have not uploaded all files.";
                    }
                }
                var userDetailsObj = db.UserDetails.Where(u => u.Id.Equals(obj.Id)).FirstOrDefault();
                var loanObj = db.Loans.Where(l => l.Id.Equals(obj.Id)).FirstOrDefault();
                userDetailsObj.AccountNumber = 1000 + Convert.ToInt32(obj.Id);
                loanObj.ApprovalStatus = "Tentative";
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Message = "Folder " + id.ToString() + "  already exists!";
            }

            return View();
        }
    }
}

HomeLoanCaseStudy/Controllers/HomeController.cs
using HomeLoanCaseStudy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeLoanCaseStudy.Controllers
{
    public class HomeController : Controller
    {
        private readonly HomeLoanDbContext db = new HomeLoanDbContext();

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
                if (obj.UserRole == "Admin")
                {
                    return RedirectToAction("Admin");
                }
                else
                {
                    var userDetailsObj = db.UserDetails.Where(ud => ud.Id.Equals(obj.Id)).FirstOrDefault();
                    var loanObj = db.Loans.Where(l => l.Id.Equals(obj.Id)).FirstOrDefault();

                    var tables = new SingleUserViewModel
                    {
                        User = obj,
                        UserDetails = userDetailsObj,
                        Loan = loanObj,
                    };

                    return View(tables);
                }
            }
            return View();
        }

        [Authorize]
        public ActionResult Admin()
        {
            if (User.Identity.IsAuthenticated)
            {
                var obj = db.Users.Where(u => u.EmailAddress.Equals(User.Identity.Name)).FirstOrDefault();
                if (obj.UserRole == "Admin")
                {
                    var tables = new UserViewModel
                    {
                        Users = db.Users.ToList(),
                        UserDetails = db.UserDetails.ToList(),
                        Loans = db.Loans.ToList()
                    };

                    return View(tables);
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HomeLoanCaseStudy/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HomeLoanCaseStudy/Views/Home/Admin.cshtml
@model HomeLoanCaseStudy.Models.UserViewModel

@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container text-black">
    <div class="row">
        <div class="col-md-6 position-absolute top-50 start-50 translate-middle">
            <div class="card card-body">
                <h2 class="display-5 fw-normal text-center text-primary">Users List</h2>
                <div class="container mb-2">
                    <hr class="bg-primary" />
                    <table class="table table-hover">
                        <thead class="table-primary">
                            <tr>
                                <th scope="col">Account No.
                                <th scope="col">Name</th>
                                <th scope="col">Email ID</th>
                                <th scope="col">Approval Status</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Users)
                            {
                                if (item.UserRole == "Admin")
                                {
                                    continue;
                                }
                                else
                                {
                                    <tr>
                                        <td>@Model.UserDetails.First(ud => ud.Id == item.Id).AccountNumber</td>
                                        <td>@item.FirstName @item.LastName</td>
                                        <td>@item.EmailAddress</td>
                                        <td>@Model.Loans.First(l => l.Id == item.Id).ApprovalStatus</td>
                                        <td>
                                            <a class="btn btn-primary btn-sm" href="@Url.Action("Index", "Admin", new { id = item.Id })">
                                                View<i class="fa fa-edit ms-2"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

HomeLoanCaseStudy/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HomeLoanCaseStudy/Views/Home/Index.cshtml
@model HomeLoanCaseStudy.Models.SingleUserViewModel

@{
    ViewBag.Title = "Home Page";
}

<div class="homepage">
    <div class="container text-center">
        <div class="homepage-text d-flex flex-column justify-content-center gap-1
                 position-absolute top-50 start-50 translate-middle user-select-none">
            <p class="text-white-50 bd-highlight fs-4">Easy & Simple Application Process</p>
            <h1 class="homepage-heading">Connecting<br />All Your Home Loan<br />Needs</h1>
            <hr />
            @if (User.Identity.IsAuthenticated)
            {
                if (Model.Loan.ApprovalStatus == "Approved")
                {
                    <div class="alert alert-primary">
                        Your Loan Application has been <strong>approved</strong>. Track the details below!
                    </div>
                }
                else if (Model.Loan.ApprovalStatus == "Rejected")
                {
                    <div class="alert alert-danger">
                        Your Loan Application has been <strong>rejected</strong>. Track the details below!
                    </div>
                }

                if (Model.UserDetails.AccountNumber != null)
                {
                    <a href="@Url.Action("Index", "LoanTracker")" class="btn btn-lg btn-primary p-3 m-4 bd-highlight">
                        Track your Application
                        <i class="fa fa-arrow-right"></i>
                    </a>
                }
                else
                {
                    <a href="@Url.Action("Index", "Application")" class="btn btn-lg btn-primary p-3 m-4 bd-highlight">
                        Apply Now
                        <i class="fa fa-arrow-right"></i>
                    </a>
                }
            }
            else
            {
                <a href="@Url.Action("Index", "Application")" class="btn btn-lg btn-primary p-3 m-4 bd-highlight">
                    Apply Now
                    <i class="fa fa-arrow-right"></i>
                </a>
            }
        </div>
    </div>
</div>